<Project>
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <LangVersion>14.0</LangVersion>
    <Deterministic>true</Deterministic>
    <DebugType>portable</DebugType>
    <VersionPrefix>1.1.0</VersionPrefix>
    <VersionSuffix Condition="'$(NavigationPublicRelease)' != 'true'">dev.8</VersionSuffix>
    <IsPackable>false</IsPackable>
    <RestorePackagesWithLockFile>true</RestorePackagesWithLockFile>
    <NuGetLockFilePath Condition="'$(RuntimeIdentifier)' != ''">$(MSBuildProjectDirectory)/obj/packages.$(RuntimeIdentifier).lock.json</NuGetLockFilePath>
    <ContinuousIntegrationBuild Condition="'$(CI)' == 'true'">true</ContinuousIntegrationBuild>
    <ContinuousIntegrationBuild Condition="'$(NavigationPublicRelease)' == 'true'">true</ContinuousIntegrationBuild>
    <RepositoryType>git</RepositoryType>
    <RepositoryUrl>https://github.com/Grzegorz1223/MVVMCompass</RepositoryUrl>
    <PackageProjectUrl>https://github.com/Grzegorz1223/MVVMCompass</PackageProjectUrl>
    <PublishRepositoryUrl>true</PublishRepositoryUrl>
    <EmbedUntrackedSources>true</EmbedUntrackedSources>
  </PropertyGroup>
</Project>
